server:
  port: 8083

spring:
  profiles:
    active: prod
  application:
    name: millions-demo
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 1024MB

  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: INPUT

logging:
  file:
    name: ./logs/${spring.application.name}.log
  level:
    come.zhouyu.mapper: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


